project:
  type: website
  output-dir: docs

website:
  title: "Science impacts on Antarctica"
  sidebar:
    contents: notebooks
    floating: true
  page-navigation: true

format:
  html:
    theme: morph
    toc: true
    df-print: kable
